/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * cfreact-template core API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../../../generated/api/users/users.validator';
import type { CreateUserContext } from '../../../generated/api/users/users.context';
import { CreateUserBody } from '../../../generated/api/users/users.zod';

import type { operations } from '@cfreact-template/core/generated/api/openapi';

import type { UsersService } from '../users.service';
import {
  assertNever,
  createUserSuccessResponse,
  emailConflictResponse,
  internalErrorResponse,
  invalidRequestResponse,
} from '../users.responses';

const factory = createFactory();

type UsersHandlerEnv = {
  Bindings: Record<string, never>;
  Variables: { usersService: UsersService };
};

/** coreのユーザー作成操作を内部HTTP契約へ変換する。 */
export const createUserHandlers = factory.createHandlers(
  zValidator('json', CreateUserBody),
  async (c: CreateUserContext<UsersHandlerEnv>) => {
    const result = await c.var.usersService.create(c.req.valid('json'));
    if (result.ok) {
      return c.json(
        createUserSuccessResponse(
          result.value
        ) satisfies operations['createUser']['responses'][201]['content']['application/json'],
        201
      );
    }

    switch (result.error.kind) {
      case 'invalid-input':
        return c.json(
          invalidRequestResponse() satisfies operations['createUser']['responses'][400]['content']['application/json'],
          400
        );
      case 'email-already-exists':
        return c.json(
          emailConflictResponse() satisfies operations['createUser']['responses'][409]['content']['application/json'],
          409
        );
      case 'persistence-failure':
        return c.json(
          internalErrorResponse() satisfies operations['createUser']['responses'][500]['content']['application/json'],
          500
        );
      default:
        return assertNever(result.error);
    }
  }
);
