/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * cfreact-template core API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../../../generated/api/users/users.validator';
import type { GetUserContext } from '../../../generated/api/users/users.context';
import { GetUserParams, GetUserResponse } from '../../../generated/api/users/users.zod';

import type { operations } from '@cfreact-template/core/generated/api/openapi';
import { guardResponseValidation } from '@cfreact-template/core/platform/http/responseValidation';

import type { UsersService } from '../users.service';
import { assertNever, internalErrorResponse, userNotFoundResponse } from '../users.responses';

const factory = createFactory();

type UsersHandlerEnv = {
  Bindings: Record<string, never>;
  Variables: { usersService: UsersService };
};

/** coreのユーザー単一取得操作を内部HTTP契約へ変換する。 */
export const getUserHandlers = factory.createHandlers(
  zValidator('param', GetUserParams),
  guardResponseValidation(),
  zValidator('response', GetUserResponse),
  async (c: GetUserContext<UsersHandlerEnv>) => {
    const { id } = c.req.valid('param');
    const result = await c.var.usersService.get(id);
    if (result.ok) {
      return c.json(
        result.value satisfies operations['getUser']['responses'][200]['content']['application/json'],
        200
      );
    }

    switch (result.error.kind) {
      case 'not-found':
        return c.json(
          userNotFoundResponse() satisfies operations['getUser']['responses'][404]['content']['application/json'],
          404
        );
      case 'persistence-failure':
        return c.json(
          internalErrorResponse() satisfies operations['getUser']['responses'][500]['content']['application/json'],
          500
        );
      default:
        return assertNever(result.error);
    }
  }
);
