/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * cfreact-template API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../../../generated/api/users/users.validator';
import type { CreateUserContext } from '../../../generated/api/users/users.context';
import { CreateUserBody } from '../../../generated/api/users/users.zod';

import type { operations } from '@cfreact-template/backend/generated/api/openapi';

import type { UsersService } from '../users.service';
import {
  assertNever,
  createUserSuccessResponse,
  emailConflictResponse,
  internalErrorResponse,
  invalidRequestResponse,
} from '../users.responses';

const factory = createFactory();

type UsersHandlerEnv = {
  Bindings: Record<string, never>;
  Variables: {
    usersService: UsersService;
  };
};

/**
 * ユーザー作成操作を契約済み HTTP 応答へ変換する処理担当を公開する。
 *
 * @remarks
 * `Orval` が生成する検証処理とコンテキストを入力として受け、`UsersService.create` の結果に応じた
 * 201、400、409、500 応答を返す。実行時には D1 登録と任意の通知送信が発生する。
 * 予期される失敗は安全な応答へ変換し、成功応答が生成スキーマに違反した場合だけ例外を上位へ渡す。
 *
 * @example
 * ```ts
 * app.route('/', generatedUsersApi);
 * ```
 */
export const createUserHandlers = factory.createHandlers(
  zValidator('json', CreateUserBody),
  async (c: CreateUserContext<UsersHandlerEnv>) => {
    // 生成された検証処理を通った JSON をサービスへ渡し、ハンドラーでは業務処理を再実装しない。
    const result = await c.var.usersService.create(c.req.valid('json'));
    if (result.ok) {
      // `Orval` が検証しない 201 応答を生成スキーマで検証し、契約違反は `app.onError` へ送る。
      return c.json(
        createUserSuccessResponse(
          result.value
        ) satisfies operations['createUser']['responses'][201]['content']['application/json'],
        201
      );
    }

    // サービスの閉じた失敗型を全種類処理し、内部原因を応答へ含めない。
    switch (result.error.kind) {
      case 'invalid-input':
        return c.json(
          invalidRequestResponse() satisfies operations['createUser']['responses'][400]['content']['application/json'],
          400
        );
      case 'email-already-exists':
        return c.json(
          emailConflictResponse() satisfies operations['createUser']['responses'][409]['content']['application/json'],
          409
        );
      case 'persistence-failure':
        return c.json(
          internalErrorResponse() satisfies operations['createUser']['responses'][500]['content']['application/json'],
          500
        );
      default:
        return assertNever(result.error);
    }
  }
);
