/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * cfreact-template API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../../../generated/api/users/users.validator';
import type { GetUserContext } from '../../../generated/api/users/users.context';
import { GetUserParams, GetUserResponse } from '../../../generated/api/users/users.zod';

import type { operations } from '@cfreact-template/backend/generated/api/openapi';
import { guardResponseValidation } from '@cfreact-template/backend/platform/http/responseValidation';

import type { UsersService } from '../users.service';
import { assertNever, internalErrorResponse, userNotFoundResponse } from '../users.responses';

const factory = createFactory();

type UsersHandlerEnv = {
  Bindings: Record<string, never>;
  Variables: {
    usersService: UsersService;
  };
};

/**
 * ユーザー単一取得操作を契約済み HTTP 応答へ変換する処理担当を公開する。
 *
 * @remarks
 * `Orval` が生成するパス検証処理とコンテキストを入力として受け、`UsersService.get` の結果に応じた
 * 200、404、500 応答を返す。実行時には D1 読み取りが発生する。未存在と予期される永続化失敗は
 * 安全な応答へ変換し、成功応答が生成スキーマに違反した場合だけ例外を上位へ渡す。
 *
 * @example
 * ```ts
 * app.route('/', generatedUsersApi);
 * ```
 */
export const getUserHandlers = factory.createHandlers(
  zValidator('param', GetUserParams),
  guardResponseValidation(),
  zValidator('response', GetUserResponse),
  async (c: GetUserContext<UsersHandlerEnv>) => {
    // 生成された検証処理が型付けしたパス引数をサービスへ渡し、リポジトリへ直接アクセスしない。
    const { id } = c.req.valid('param');
    const result = await c.var.usersService.get(id);
    if (result.ok) {
      return c.json(
        result.value satisfies operations['getUser']['responses'][200]['content']['application/json'],
        200
      );
    }

    // サービスの未存在・永続化失敗を、それぞれ安全な公開エラーへ網羅変換する。
    switch (result.error.kind) {
      case 'not-found':
        return c.json(
          userNotFoundResponse() satisfies operations['getUser']['responses'][404]['content']['application/json'],
          404
        );
      case 'persistence-failure':
        return c.json(
          internalErrorResponse() satisfies operations['getUser']['responses'][500]['content']['application/json'],
          500
        );
      default:
        return assertNever(result.error);
    }
  }
);
