/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * cfreact-template API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../../../generated/api/users/users.validator';
import type { ListUsersContext } from '../../../generated/api/users/users.context';
import { ListUsersResponse } from '../../../generated/api/users/users.zod';

import type { operations } from '@cfreact-template/backend/generated/api/openapi';
import { guardResponseValidation } from '@cfreact-template/backend/platform/http/responseValidation';

import type { UsersService } from '../users.service';
import { internalErrorResponse } from '../users.responses';

const factory = createFactory();

type UsersHandlerEnv = {
  Bindings: Record<string, never>;
  Variables: {
    usersService: UsersService;
  };
};

/**
 * ユーザー一覧操作を契約済み HTTP 応答へ変換する処理担当を公開する。
 *
 * @remarks
 * `Orval` が生成する応答検証処理とコンテキストを入力として受け、`UsersService.list` の結果に応じた
 * 200 または 500 応答を返す。実行時には D1 読み取りが発生する。予期される永続化失敗は安全な応答へ
 * 変換し、成功応答が生成スキーマに違反した場合だけ例外を上位へ渡す。
 *
 * @example
 * ```ts
 * app.route('/', generatedUsersApi);
 * ```
 */
export const listUsersHandlers = factory.createHandlers(
  guardResponseValidation(),
  zValidator('response', ListUsersResponse),
  async (c: ListUsersContext<UsersHandlerEnv>) => {
    // `usersService` だけをコンテキストから取得し、データベースバインディングやリポジトリをハンドラーへ露出しない。
    const result = await c.var.usersService.list();
    if (result.ok) {
      return c.json(
        result.value satisfies operations['listUsers']['responses'][200]['content']['application/json'],
        200
      );
    }

    // 一覧取得の唯一の失敗である永続化失敗を、安全な固定応答へ変換して内部原因を公開しない。
    return c.json(
      internalErrorResponse() satisfies operations['listUsers']['responses'][500]['content']['application/json'],
      500
    );
  }
);
