/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * cfreact-template API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../../../generated/api/health/health.validator';
import type { GetHealthContext } from '../../../generated/api/health/health.context';
import { GetHealthResponse } from '../../../generated/api/health/health.zod';

import type { operations } from '@cfreact-template/main/backend/generated/api/openapi';
import { guardResponseValidation } from '@cfreact-template/main/backend/platform/http/responseValidation';

const factory = createFactory();

type HealthHandlerEnv = {
  Bindings: Record<string, never>;
};

/**
 * 稼働確認操作を契約済み HTTP 応答へ変換する処理担当を公開する。
 *
 * @remarks
 * `Orval` が生成する応答検証処理とコンテキストを入力として受け、`Cloudflare Workers` が応答可能であることを固定状態と
 * 現在時刻で返す。現在時刻の読み取り以外に外部副作用はなく、通常は例外を送出しない。組み立てた応答が
 * 生成スキーマに違反した場合だけ例外を上位へ渡す。
 *
 * @example
 * ```ts
 * app.route('/', generatedHealthApi);
 * ```
 */
export const getHealthHandlers = factory.createHandlers(
  guardResponseValidation(),
  zValidator('response', GetHealthResponse),
  async (c: GetHealthContext<HealthHandlerEnv>) => {
    // `status` は `TypeSpec` のリテラル契約に合わせ、時刻だけを実行時に生成する。
    return c.json(
      {
        status: 'ok',
        timestamp: new Date().toISOString(),
      } satisfies operations['getHealth']['responses'][200]['content']['application/json'],
      200
    );
  }
);
