/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * cfreact-template API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../../../generated/api/users/users.validator';
import type { CreateUserContext } from '../../../generated/api/users/users.context';
import { CreateUserBody } from '../../../generated/api/users/users.zod';

import type { operations } from '@cfreact-template/main/backend/generated/api/openapi';
import type { CoreSdk } from '@cfreact-template/core-sdk';

import {
  assertNever,
  createUserSuccessResponse,
  emailConflictResponse,
  internalErrorResponse,
  invalidRequestResponse,
} from '../users.responses';

const factory = createFactory();

type UsersHandlerEnv = {
  Bindings: Record<string, never>;
  Variables: {
    coreSdk: CoreSdk;
  };
};

/**
 * ユーザー作成操作を契約済み HTTP 応答へ変換する処理担当を公開する。
 *
 * @remarks
 * 検証済み入力をcore SDKへ渡し、core結果をmain公開契約の201、400、409、500応答へ変換する。
 *
 * @example
 * ```ts
 * app.route('/', generatedUsersApi);
 * ```
 */
export const createUserHandlers = factory.createHandlers(
  zValidator('json', CreateUserBody),
  async (c: CreateUserContext<UsersHandlerEnv>) => {
    const result = await c.var.coreSdk.createUser(c.req.valid('json'));

    switch (result.status) {
      case 201:
        return c.json(
          createUserSuccessResponse(
            result.data
          ) satisfies operations['createUser']['responses'][201]['content']['application/json'],
          201
        );
      case 400:
        return c.json(
          invalidRequestResponse() satisfies operations['createUser']['responses'][400]['content']['application/json'],
          400
        );
      case 409:
        return c.json(
          emailConflictResponse() satisfies operations['createUser']['responses'][409]['content']['application/json'],
          409
        );
      case 500:
        return c.json(
          internalErrorResponse() satisfies operations['createUser']['responses'][500]['content']['application/json'],
          500
        );
      default:
        return assertNever(result);
    }
  }
);
