/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * cfreact-template API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../../../generated/api/users/users.validator';
import type { GetUserContext } from '../../../generated/api/users/users.context';
import { GetUserParams, GetUserResponse } from '../../../generated/api/users/users.zod';

import type { operations } from '@cfreact-template/main/backend/generated/api/openapi';
import { guardResponseValidation } from '@cfreact-template/main/backend/platform/http/responseValidation';
import type { CoreSdk } from '@cfreact-template/core-sdk';

import {
  assertNever,
  internalErrorResponse,
  invalidRequestResponse,
  userNotFoundResponse,
} from '../users.responses';

const factory = createFactory();

type UsersHandlerEnv = {
  Bindings: Record<string, never>;
  Variables: {
    coreSdk: CoreSdk;
  };
};

/**
 * ユーザー単一取得操作を契約済み HTTP 応答へ変換する処理担当を公開する。
 *
 * @remarks
 * 検証済みIDをcore SDKへ渡し、coreの認証失敗を含む結果をmain公開契約の200、400、404、500応答へ変換する。
 *
 * @example
 * ```ts
 * app.route('/', generatedUsersApi);
 * ```
 */
export const getUserHandlers = factory.createHandlers(
  zValidator('param', GetUserParams),
  guardResponseValidation(),
  zValidator('response', GetUserResponse),
  async (c: GetUserContext<UsersHandlerEnv>) => {
    const { id } = c.req.valid('param');
    const result = await c.var.coreSdk.getUser(id);

    switch (result.status) {
      case 200:
        return c.json(
          result.data satisfies operations['getUser']['responses'][200]['content']['application/json'],
          200
        );
      case 400:
        return c.json(
          invalidRequestResponse() satisfies operations['getUser']['responses'][400]['content']['application/json'],
          400
        );
      case 404:
        return c.json(
          userNotFoundResponse() satisfies operations['getUser']['responses'][404]['content']['application/json'],
          404
        );
      // 内部通信の認証失敗は利用者の認証状態として公開せず、構成不備の固定500へ変換する。
      case 401:
      case 500:
        return c.json(
          internalErrorResponse() satisfies operations['getUser']['responses'][500]['content']['application/json'],
          500
        );
      default:
        return assertNever(result);
    }
  }
);
