/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * cfreact-template API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../../../generated/api/users/users.validator';
import type { ListUsersContext } from '../../../generated/api/users/users.context';
import { ListUsersResponse } from '../../../generated/api/users/users.zod';

import type { operations } from '@cfreact-template/main/backend/generated/api/openapi';
import { guardResponseValidation } from '@cfreact-template/main/backend/platform/http/responseValidation';
import type { CoreSdk } from '@cfreact-template/core-sdk';

import { internalErrorResponse } from '../users.responses';

const factory = createFactory();

type UsersHandlerEnv = {
  Bindings: Record<string, never>;
  Variables: {
    coreSdk: CoreSdk;
  };
};

/**
 * ユーザー一覧操作を契約済み HTTP 応答へ変換する処理担当を公開する。
 *
 * @remarks
 * core SDKの結果をmain公開契約の200または500応答へ変換する。coreの内部本文は公開しない。
 *
 * @example
 * ```ts
 * app.route('/', generatedUsersApi);
 * ```
 */
export const listUsersHandlers = factory.createHandlers(
  guardResponseValidation(),
  zValidator('response', ListUsersResponse),
  async (c: ListUsersContext<UsersHandlerEnv>) => {
    const result = await c.var.coreSdk.listUsers();
    if (result.status === 200) {
      return c.json(
        result.data satisfies operations['listUsers']['responses'][200]['content']['application/json'],
        200
      );
    }

    return c.json(
      internalErrorResponse() satisfies operations['listUsers']['responses'][500]['content']['application/json'],
      500
    );
  }
);
