/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * cfreact-template core API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../../../generated/api/users/users.validator';
import type { ListUsersContext } from '../../../generated/api/users/users.context';
import { ListUsersResponse } from '../../../generated/api/users/users.zod';

import type { operations } from '@cfreact-template/core/generated/api/openapi';
import { guardResponseValidation } from '@cfreact-template/core/platform/http/responseValidation';

import type { UsersService } from '../users.service';
import { internalErrorResponse } from '../users.responses';

const factory = createFactory();

type UsersHandlerEnv = {
  Bindings: Record<string, never>;
  Variables: { usersService: UsersService };
};

/** coreのユーザー一覧操作を内部HTTP契約へ変換する。 */
export const listUsersHandlers = factory.createHandlers(
  guardResponseValidation(),
  zValidator('response', ListUsersResponse),
  async (c: ListUsersContext<UsersHandlerEnv>) => {
    const result = await c.var.usersService.list();
    if (result.ok) {
      return c.json(
        result.value satisfies operations['listUsers']['responses'][200]['content']['application/json'],
        200
      );
    }

    return c.json(
      internalErrorResponse() satisfies operations['listUsers']['responses'][500]['content']['application/json'],
      500
    );
  }
);
