/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * cfreact-template API
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../../../generated/api/hello/hello.validator';
import type { GetHelloContext } from '../../../generated/api/hello/hello.context';
import { GetHelloResponse } from '../../../generated/api/hello/hello.zod';

import type { operations } from '@cfreact-template/main/backend/generated/api/openapi';
import { guardResponseValidation } from '@cfreact-template/main/backend/platform/http/responseValidation';

const factory = createFactory();

type HelloHandlerEnv = {
  Bindings: Record<string, never>;
};

/**
 * 挨拶取得操作を契約済み HTTP 応答へ変換する処理担当を公開する。
 *
 * @remarks
 * `Orval` が生成する応答検証処理とコンテキストを入力として受け、`TypeSpec` の成功応答を返す。
 * 現在時刻の読み取り以外に外部副作用はなく、通常は例外を送出しない。組み立てた応答が生成スキーマに
 * 違反した場合だけ例外を上位へ渡す。
 *
 * @example
 * ```ts
 * app.route('/', generatedHelloApi);
 * ```
 */
export const getHelloHandlers = factory.createHandlers(
  guardResponseValidation(),
  zValidator('response', GetHelloResponse),
  async (c: GetHelloContext<HelloHandlerEnv>) => {
    // 現在時刻を ISO 8601 へ変換し、`TypeSpec` の `HelloResponse` 形状で返す。
    return c.json(
      {
        message: 'Hello from Hono + Cloudflare Workers',
        timestamp: new Date().toISOString(),
      } satisfies operations['getHello']['responses'][200]['content']['application/json'],
      200
    );
  }
);
